---
- name: Main Playbook
  hosts: localhost
  gather_facts: true  # Ensure platform facts are gathered
  become: true        # Required for sudo on Ubuntu

  tasks:
    - name: Include macOS tasks
      include_tasks: tasks/macos-packages.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include Ubuntu tasks
      include_tasks: tasks/ubuntu-packages.yml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Oh My Zsh
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: ~/.oh-my-zsh

    # Switch main shell to zsh
    - name: Change default shell to zsh
      ansible.builtin.shell: chsh -s $(which zsh)

#- import_playbook: tasks/install-python.yml
#- import_playbook: tasks/setup-ssh.yml
#- import_playbook: tasks/clone-lilydevtools.yml