---
- name: Main Playbook
  hosts: localhost
  gather_facts: true  # Ensure platform facts are gathered
  become: true        # Required for sudo on Ubuntu

  tasks:
    - name: Include macOS tasks
      include_tasks: tasks/macos-packages.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include Ubuntu tasks
      include_tasks: tasks/ubuntu-packages.yml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Oh My Zsh
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: ~/.oh-my-zsh

    - name: Ensure zsh-autosuggestions is installed
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: Ensure zsh-syntax-highlighting is installed
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

    - name: Install Powerlevel10k theme
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: master

    # Switch main shell to zsh
    - name: Change default shell to zsh
      ansible.builtin.shell: chsh -s $(which zsh)

    - name: Include dotfiles tasks
      include_tasks: tasks/dotfiles.yml

- import_playbook: tasks/install-python.yml
#- import_playbook: tasks/setup-ssh.yml
#- import_playbook: tasks/clone-lilydevtools.yml