---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - 1password
        - docker
        - iterm2
        - telegram
        - visual-studio-code
        - vlc
        - microsoft-edge


#- import_playbook: tasks/ohmyzsh.yml
#- import_playbook: tasks/dotfiles.yml
- import_playbook: tasks/zoxide.yml