---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - curl
        - unzip
      become: true



- import_playbook: tasks/nerdfonts.yml