---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Debug home directory
      ansible.builtin.debug:
        msg: "Home directory is {{ ansible_env.HOME }}"

    - name: Install yay AUR helper
      block:
        - name: Remove existing yay directory if exists
          ansible.builtin.file:
            path: /tmp/yay
            state: absent

        - name: Clone yay repository
          ansible.builtin.git:
            repo: https://aur.archlinux.org/yay.git
            dest: /tmp/yay

        - name: Build yay package
          ansible.builtin.shell: makepkg -s --noconfirm
          args:
            chdir: /tmp/yay

        - name: Install yay package
          ansible.builtin.shell: sudo pacman -U --noconfirm /tmp/yay/yay-*.pkg.tar.*
          args:
            chdir: /tmp/yay
      register: yay_install_result
      when: ansible_facts.packages['yay'] is not defined or not ansible_facts.packages['yay']

    - name: Show yay installation stdout
      ansible.builtin.debug:
        var: yay_install_result.stdout

    - name: Show yay installation stderr
      ansible.builtin.debug:
        var: yay_install_result.stderr
      
- import_playbook: tasks/asdf.yml
#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'