---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Change default shell to zsh
      ansible.builtin.shell: chsh -s $(which zsh) "{{ current_user.stdout }}"
      become: true


- import_playbook: tasks/install-python.yml