---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Debug home directory
      ansible.builtin.debug:
        var: ansible_env.HOME

    #- name: Install yay AUR helper interactively
    #  ansible.builtin.shell: |
    #    if ! command -v yay &> /dev/null; then
    #      cd /tmp
    #      git clone https://aur.archlinux.org/yay.git
    #      cd yay
    #      makepkg -si --noconfirm
    #      rm -rf /tmp/yay
    #    fi
    #  args:
    #    executable: /bin/bash
    #  when: ansible_os_family == "Archlinux"
    #  register: yay_install_result
#
    #- name: Show yay installation stdout
    #  ansible.builtin.debug:
    #    var: yay_install_result.stdout
    #  when: ansible_os_family == "Archlinux"
#
    #- name: Show yay installation stderr
    #  ansible.builtin.debug:
    #    var: yay_install_result.stderr
    #  when: ansible_os_family == "Archlinux"
      
- import_playbook: tasks/install-yay.yml
- import_playbook: tasks/asdf.yml
#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'