---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Debug home directory
      ansible.builtin.debug:
        msg: "Home directory is {{ ansible_env.HOME }}"

    - name: Install yay AUR helper
      ansible.builtin.shell: |
        if ! command -v yay &> /dev/null; then
          cd /tmp
          git clone https://aur.archlinux.org/yay.git
          cd yay
          makepkg -si --noconfirm
          rm -rf /tmp/yay
        fi
#      register: yay_install_result
#      changed_when: yay_install_result.stdout is search('installing yay') or yay_install_result.rc == 0
      
- import_playbook: tasks/asdf.yml
#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'