---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Include yay tasks
      include_tasks: tasks/install-yay.yml
      
- import_playbook: tasks/asdf.yml
#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'