---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Check if Meslo fonts directory exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/share/fonts/Meslo"
      register: meslo_fonts

    - name: Include font installation playbook
      include_tasks: nerdfonts.yml
      when: not meslo_fonts.stat.exists

