---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Include dotfiles tasks
      include_tasks: tasks/dotfiles.yml

- import_playbook: tasks/install-python.yml