---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Debug home directory
      ansible.builtin.debug:
        var: ansible_env.HOME
  
    - name: Include macOS apps
      include_tasks: apps-macos.yml
      when: ansible_facts['os_family'] == 'Darwin'


      
#- import_playbook: tasks/install-yay.yml
#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'