---
- name: Test install packages with homebrew cask
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - name: Debug home directory
      ansible.builtin.debug:
        msg: "Home directory is {{ ansible_env.HOME }}"
      


- name: Install macOS apps
  import_playbook: tasks/apps-macos.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Ubuntu apps
  import_playbook: tasks/apps-ubuntu.yml
  when: ansible_facts['os_family'] == 'Debian'

#- import_playbook: tasks/dotfiles.yml
#- import_playbook: tasks/zoxide.yml
#- name: Import macOS specific playbook
#  import_playbook: macos_playbook.yml
#  when: ansible_facts['os_family'] == 'Darwin'