---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Check if any Meslo* files exist in $HOME/.local/share/fonts
      ansible.builtin.find:
        paths: "{{ ansible_env.HOME }}/.local/share/fonts"
        patterns: "Meslo*"
      register: meslo_files

    - name: Include font installation playbook
      include_tasks: tasks/nerdfonts.yml
      when: meslo_files.matched == 0

