---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Check if the PyEnv3.9 conda environment exists
      ansible.builtin.shell: conda env list | grep -q 'PyEnv3.9'
      register: conda_env_check
      failed_when: false
      changed_when: false
      environment:
        PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/miniconda/bin"

    - name: Debug conda_env_check
      ansible.builtin.debug:
        var: conda_env_check