---

- name: Download Miniconda installer
  ansible.builtin.get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: $HOME/Miniconda3-latest-Linux-x86_64.sh
    mode: '0755'

- name: Run Miniconda installer
  ansible.builtin.shell: bash $HOME/Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda

  # todo: remove installer after installation

