---

- name: Debug ansible path
  ansible.builtin.debug:
    msg: "ansible_env.PATH? {{ ansible_env.PATH }}"

- name: Install apps
  ansible.builtin.homebrew:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - 1password
    - docker
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack
