---

- name: Debug ansible path
  ansible.builtin.debug:
    msg: "ansible_env.PATH? {{ ansible_env.PATH }}"

- name: Install apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    path: /opt/homebrew/bin
    state: present
  ignore_errors: yes
  with_items:
    - 1password
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack

- name: Install Docker
  community.general.homebrew_cask:
    name: docker
    state: present
    register: result
  ignore_errors: yes