---

- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_check

- name: Debug homebrew check
  ansible.builtin.debug:
    msg: "Homebrew available? {{ homebrew_check }}"

- name: Install apps
  ansible.builtin.homebrew:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - 1password
    - docker
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack
