---

- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    path: /opt/homebrew/bin
    state: present
  ignore_errors: yes
  with_items:
    - 1password
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack

- name: Install Docker Desktop for macOS
  community.general.homebrew_cask:
    name: docker
    path: /opt/homebrew/bin
    state: present

- name: Install Docker CLI tools
  community.general.homebrew:
    name: "{{ item }}"
    path: /opt/homebrew/bin
    state: present
  with_items:
    - docker-compose
    - docker-buildx
