---

- name: Install Apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    path: /opt/homebrew/bin
    state: present
  ignore_errors: yes
  with_items:
    - 1password
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack
