---

- name: Check Homebrew bin folder
  ansible.builtin.command: ls /opt/homebrew/bin/
  register: homebrew_check
  failed_when: false
  changed_when: false

- name: Debug homebrew check
  ansible.builtin.debug:
    msg: "Homebrew available? {{ homebrew_check }}"

- name: Install apps
  ansible.builtin.homebrew:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - 1password
    - docker
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack
  environment:
        PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin"
