---

- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_check
  failed_when: false
  changed_when: false

- name: Install Homebrew
  include_role:
    name: geerlingguy.mac.homebrew
  when: homebrew_check.rc != 0

- name: Ensure Homebrew bin is in PATH
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root
  when: homebrew_check.rc != 0

- name: Debug ansible path
  ansible.builtin.debug:
    msg: "ansible_env.PATH? {{ ansible_env.PATH }}"

- name: Install apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    path: /opt/homebrew/bin
    state: present
  ignore_errors: yes
  with_items:
    - 1password
    - iterm2
    - telegram
    - visual-studio-code
    - vlc
    - microsoft-edge
    - slack
    - docker
