---

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
  become: true

- name: Install packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - unzip
    - bat
    - ffmpeg
    - fzf
    - git
    - eza
    - vim
    - zsh
    - xclip
    - wget
  become: true

- name: Install base-devel (required for AUR packages)
  community.general.pacman:
    name: base-devel
    state: present
  become: true

- name: Install yay AUR helper
  ansible.builtin.shell: |
    if ! command -v yay &> /dev/null; then
      cd /tmp
      git clone https://aur.archlinux.org/yay.git
      cd yay
      makepkg -si --noconfirm
      rm -rf /tmp/yay
    fi
  register: yay_install_result
  changed_when: yay_install_result.stdout is search('installing yay') or yay_install_result.rc == 0