---

- name: Update pacman cache
  community.general.pacman:
    update_cache: yes
  become: true

- name: Install packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - unzip
    - bat
    - ffmpeg
    - fzf
    - git
    - eza
    - vim
    - zsh
    - xclip
    - wget
  become: true
