---
- name: Download asdf archive from GitHub releases
  ansible.builtin.get_url:
    url: "https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz"
    dest: "/tmp/asdf-v0.18.0-linux-amd64.tar.gz"
    mode: '0644'

- name: Create temporary extraction directory
  ansible.builtin.file:
    path: "/tmp/asdf-extract"
    state: directory
    mode: '0755'

- name: Extract asdf archive to temporary directory
  ansible.builtin.unarchive:
    src: "/tmp/asdf-v0.18.0-linux-amd64.tar.gz"
    dest: "/tmp/asdf-extract"
    remote_src: yes

- name: Find asdf binary in extracted archive
  ansible.builtin.find:
    paths: "/tmp/asdf-extract"
    patterns: "asdf"
    file_type: file
    recurse: yes
  register: asdf_binary_search

- name: Create local bin directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Copy asdf binary to PATH directory
  ansible.builtin.copy:
    src: "{{ asdf_binary_search.files[0].path }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/asdf"
    mode: '0755'
    remote_src: yes
  when: asdf_binary_search.files | length > 0

- name: Add ~/.local/bin to PATH in ~/.zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/asdf-v0.18.0-linux-amd64.tar.gz"
    - "/tmp/asdf-extract"