---
- name: Install asdf
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install asdf on Ubuntu
      debug:
        msg: "TODO: Install asdf on Ubuntu"
      when: ansible_os_family == "Debian"

    - name: Install asdf on Arch
      ansible.builtin.shell: |
        git clone https://aur.archlinux.org/asdf-vm.git /tmp/asdf-vm
        cd /tmp/asdf-vm
        makepkg -si --noconfirm
      args:
        creates: /usr/bin/asdf
      when: ansible_os_family == "Archlinux"

    - name: Add asdf shims to PATH in ~/.zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="$ASDF_DATA_DIR/shims:$PATH"'
        create: yes
      when: 
        - ansible_env.HOME is defined
        - "'ASDF_DATA_DIR/shims' not in lookup('file', ansible_env.HOME + '/.zshrc', errors='ignore')"

    - name: Add Node.js plugin
      ansible.builtin.shell: asdf plugin add nodejs

    - name: Install Node.js latest version
      ansible.builtin.shell: asdf install nodejs latest
      args:
        executable: /bin/zsh

    - name: Set global Node.js version
      ansible.builtin.shell: zsh -l -c "asdf set nodejs latest"
