---

- name: Setup dotfiles
  ansible.builtin.copy:
    src: "dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    mode: '0644'
  loop:
    - .zshrc
    - .p10k.zsh
    - .bat.conf
    - .ideavimrc
    - .vimrc
