
---
- name: Setup Python Environment
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install Miniconda on Ubuntu
      include_tasks: python/conda-ubuntu.yml
      when: ansible_facts['os_family'] == 'Debian'
    
    - name: Install Miniconda on MacOS
      include_tasks: python/conda-macos.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Check if conda is already initialized in .zshrc
      ansible.builtin.command: grep -q 'conda_setup' "{{ ansible_env.HOME }}/.zshrc"
      register: conda_init_check
      failed_when: false
      changed_when: false

    - name: Add conda binary path to PATH and initialize conda
      ansible.builtin.shell: |
        if [ -d "$HOME/miniconda3/bin" ]; then
          export PATH="$PATH:$HOME/miniconda3/bin"
        elif [ -d "$HOME/miniconda/bin" ]; then
          export PATH="$PATH:$HOME/miniconda/bin"
        fi
        conda init --all
      when: conda_init_check.rc != 0
    
    - name: Activate conda
      ansible.builtin.shell: |
        if [ -d "$HOME/miniconda3/bin" ]; then
          source "{{ ansible_env.HOME }}/miniconda3/bin/activate"
        elif [ -d "$HOME/miniconda/bin" ]; then
          source "{{ ansible_env.HOME }}/miniconda/bin/activate"
        fi

    - name: Check if the PyEnv3.9 conda environment exists
      ansible.builtin.command: conda env list | grep -q '^PyEnv3\.9 '
      register: conda_env_check
      failed_when: false
      changed_when: false

    - name: Create Python 3.9 environment
      ansible.builtin.shell: conda create --name PyEnv3.9 python=3.9 -y
      when: conda_env_check.rc != 0

    - name: Append conda activate to ~/.zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'conda activate PyEnv3.9'
        create: yes
      when: 
        - ansible_env.HOME is defined
        - "'conda activate PyEnv3.9' not in lookup('file', ansible_env.HOME + '/.zshrc', errors='ignore')"

    - name: Install required Python packages
      ansible.builtin.shell: |
        conda run -n PyEnv3.9 pip install pyperclip beautifulsoup4 requests
      args:
        executable: /bin/zsh