---
- hosts: arch
  become: yes
  roles:
    - role: jpedrodelacerda.yay
      vars:
        homedir: "{{ ansible_env.HOME }}"
        srcdir: "{{ ansible_env.HOME }}/.src"

  tasks:
    - name: Install AUR package with yay
      yay:
        name: visual-studio-code-bin
        state: present
