---
- name: Install Apps
  hosts: localhost
  gather_facts: true
  environment:
    PATH: /opt/homebrew/bin:{{ ansible_env.PATH }}

  tasks:
    - name: Include macOS apps
      include_tasks: apps-macos.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include Ubuntu apps
      include_tasks: apps-ubuntu.yml
      when: ansible_facts['os_family'] == 'Debian'