
---
- name: Setup Python Environment
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install Miniconda on macOS
      include_tasks: python/conda-macos.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install Miniconda on Ubuntu
      include_tasks: python/conda-ubuntu.yml
      when: ansible_facts['os_family'] == 'Debian'

    - name: Debug home directory
      ansible.builtin.debug:
        msg: "Home directory is {{ ansible_env.HOME }}"

    - name: Check if conda is already initialized in .zshrc
      ansible.builtin.command: grep -q 'conda_setup' "{{ ansible_env.HOME }}/.zshrc"
      register: conda_init_check
      failed_when: false
      changed_when: false

    - name: Initialize conda
      ansible.builtin.shell: $HOME/miniconda/bin/conda init zsh
      when: conda_init_check.rc != 0

    - name: Check if the PyEnv3.9 conda environment exists
      ansible.builtin.command: $HOME/miniconda/bin/conda env list | grep -q '^PyEnv3\.9 '
      register: conda_env_check
      failed_when: false
      changed_when: false

    - name: Create Python 3.9 environment
      ansible.builtin.shell: $HOME/miniconda/bin/conda create --name PyEnv3.9 python=3.9 -y
      when: conda_env_check.rc != 0

    - name: Append conda activate to ~/.zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'conda activate PyEnv3.9'
        create: yes
      when: 
        - ansible_env.HOME is defined
        - "'conda activate PyEnv3.9' not in lookup('file', ansible_env.HOME + '/.zshrc', errors='ignore')"

