---
- hosts: arch
  become: yes
  tasks:
    - name: Install yay AUR helper
      include_role:
        name: jpedrodelacerda.yay
      vars:
        homedir: "{{ ansible_env.HOME }}"
        srcdir: "{{ ansible_env.HOME }}/.src"
