---
- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_check
  ignore_errors: true

- name: Install Homebrew if not installed
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: homebrew_check.rc != 0
  args:
    creates: /usr/local/bin/brew

- name: Update Homebrew
  ansible.builtin.command: brew update

- name: Install packages on macOS
  ansible.builtin.homebrew:
    name: "{{ item }}"
  with_items:
    - bat
    - ffmpeg
    - fzf
    - git
    - gpg
    - eza
    - vim
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - ansible
