---
- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: Install packages on macOS
  ansible.builtin.homebrew:
    name: "{{ item }}"
  with_items:
    - bat
    - ffmpeg
    - fzf
    - git
    - gpg
    - eza
    - vim
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions
    - ansible
