---
- name: Main Playbook
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install Neovim on macOS
      ansible.builtin.homebrew:
        name: neovim
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install Neovim on Ubuntu
      ansible.builtin.apt:
        name: neovim
        state: latest
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Neovim on Arch (btw)
      community.general.pacman:
        name: neovim
        state: present
      when: ansible_facts['os_family'] == 'Archlinux'
      become: true

    - name: Ensure ~/.config/nvim directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/nvim"
        state: directory

    - name: Clone nvim configuration repository
      ansible.builtin.git:
        repo: "https://github.com/lily-gh/nvim.git"
        dest: "{{ ansible_env.HOME }}/.config/nvim"
        force: yes