---

- name: Ensure font directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - $HOME/.local/share/fonts
    - $HOME/Meslo

- name: Determine archive file extension based on OS
  ansible.builtin.set_fact:
    archive_extension: >-
      {{
        (ansible_facts['os_family'] == 'Darwin') | ternary('zip', 'tar.xz')
      }}

- name: Download Meslo Nerd Fonts archive
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Meslo.{{ archive_extension }}"
    dest: "$HOME/Meslo.{{ archive_extension }}"

- name: Extract Meslo Nerd Fonts archive
  ansible.builtin.unarchive:
    src: "$HOME/Meslo.{{ archive_extension }}"
    dest: $HOME/Meslo
    remote_src: yes

- name: Set font destination based on OS
  ansible.builtin.set_fact:
    font_dest: >-
      {{
        (ansible_facts['os_family'] == 'Darwin') | ternary(ansible_env.HOME + '/Library/Fonts', ansible_env.HOME + '/.local/share/fonts')
      }}

- name: Copy specific font files to fonts directory
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/Meslo/{{ item }}"
    dest: "{{ font_dest }}/"
    remote_src: yes
  with_items:
    - MesloLGLNerdFont-Regular.ttf
    - MesloLGLDZNerdFont-Bold.ttf
    - MesloLGLDZNerdFontMono-Regular.ttf

# only in Ubuntu
- name: Refresh font cache
  ansible.builtin.command:
    cmd: fc-cache -fv
  when: ansible_facts['os_family'] == 'Debian'

- name: Remove font archive
  ansible.builtin.file:
    path: $HOME/Meslo.tar.xz
    state: absent
