---
- name: Install Rust and Zellij on Ubuntu
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Check if Rust is already installed
      ansible.builtin.command: which rustc
      register: rust_check
      failed_when: false

    - name: Install Rust via rustup
      ansible.builtin.shell: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"
      when: rust_check.rc != 0

    - name: Add Cargo bin to PATH in ~/.zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        create: yes

    - name: Source cargo environment
      ansible.builtin.shell: source {{ ansible_env.HOME }}/.cargo/env
      args:
        executable: /bin/bash
      when: rust_check.rc != 0

    - name: Check if Zellij is already installed
      ansible.builtin.command: which zellij
      register: zellij_check
      failed_when: false

    - name: Install Zellij via cargo
      ansible.builtin.shell: |
        source {{ ansible_env.HOME }}/.cargo/env && cargo install --locked zellij
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.cargo/bin/zellij"
      when: zellij_check.rc != 0