---

# eza dependencies
- name: Include eza dependencies
  include_tasks: eza-dependencies.yml
  when: ansible_facts['cmdline']['eza'] is not defined

# Update apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

# Install packages with apt
- name: Install packages on Ubuntu/WSL
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - bat
    - ffmpeg
    - fzf
    - git
    - gpg
    - eza
    - vim
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions