---

- name: Check if 'eza' command is available
  ansible.builtin.command: which eza
  register: eza_check
  failed_when: false

- name: Include eza dependencies if 'eza' is not installed
  include_tasks: eza-dependencies.yml
  when: eza_check.rc != 0

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages on Ubuntu/WSL
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - bat
    - ffmpeg
    - fzf
    - git
    - eza
    - vim
    - zsh
    - build-essential
