- name: Install zoxide and initialize it in zsh
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    zoxide_install_url: "https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh"

  tasks:
    - name: Download and install zoxide
      ansible.builtin.shell: |
        curl -sS {{ zoxide_install_url }} | bash
      args:
        creates: "{{ ansible_env.HOME }}/.zoxide"

    - name: Initialize zoxide .zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'eval "$(zoxide init zsh)"'
        insertafter: EOF
        state: present
